app:
  brand: "Institution Name"
  name: "Pay X"
  hostname: "localhost"
  email_host_name: "localhost"
  auth:
    cas_header: "CAS_HEADER"
    py_logout_url: "https://passportyork.yorku.ca/ppylogin/ppylogout"
    py_authenticated_paths: 
      - "/ppy_login"
error_notifier:
  subject_prefix: "[Pay X ERROR]"
  from_email: "errors@your.institution"
  from_name: "Pay X"
  recipients: "list_of@people.com, separated@by_commas.net"
alma:
  api_key: "override this in settings.local.yml"
  region: "override this in settings.local.yml"
  api:
    item_url: "https://api-na.hosted.exlibrisgroup.com/almaws/v1/items?item_barcode={{barcode}}"
    user_url: "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/{{user_primary_id}}"
    fee_url: "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/{{user_primary_id}}/fees/{{fee_id}}"
ypb:
  wsdl_url: https://ypbpaymentapp/?wsdl
  payment_page_url: https://ypbpaymentapp/Payment.aspx
  receipt_page_url: https://ypbpaymentapp/Receipt.aspx
  application_name: yulfines
  application_id: QATEST
  application_password:
  application_law_name: Osgoode Fines
  application_law_id:
  application_law_password:
  application_language: enUS
  transaction_types:
    purchase: CC-PURCHASE
    preauth: CC-PREAUTH
  transaction_statuses:
    approved: APPROVED
    declined: DECLINED
    cancelled: CANCELLED
